import { MatDialogRef } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import { HttpClient } from '@angular/common/http';
import { CustomErrorStateMatcher } from '../../shared/error-state-matcher';
import { FormControl } from '@angular/forms';
export declare class FilePermissionsModal {
    private dialogRef;
    private http;
    private snackBar;
    name: string;
    path: string;
    modeSym: string;
    icon: string;
    userRead: boolean;
    groupRead: boolean;
    publicRead: boolean;
    userWrite: boolean;
    groupWrite: boolean;
    publicWrite: boolean;
    userExecute: boolean;
    groupExecute: boolean;
    publicExecute: boolean;
    isDirectory: boolean;
    recursive: boolean;
    node: any;
    owner: string;
    group: string;
    octalMode: string;
    octalModePattern: string;
    matcher: CustomErrorStateMatcher;
    private readonly navigationKeys;
    constructor(data: any, dialogRef: MatDialogRef<FilePermissionsModal>, http: HttpClient, snackBar: MatSnackBar);
    makeOctalModeString(mode: number): string;
    applyFilter(filterValue: string): void;
    formatPermissions(): void;
    calcBooleanFromMode(char: string): boolean;
    updateUI(): void;
    savePermissions(): void;
    closeDialog(): void;
    onOctalModeChange(newOctalMode: string, octalModeInput: FormControl): void;
    onOctalModeKeyDown(e: KeyboardEvent): void;
    private handleErrorObservable;
}
